version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEV_OPENAI_KEY=${DEV_OPENAI_KEY}
      - MONGODB_URI=mongodb://mongodb:27017/
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
      - chromadb
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  chromadb:
    build:
      context: ./chromadb
      dockerfile: Dockerfile
    ports:
      - "8100:8000"
    volumes:
      - chromadb-data:/chroma/data
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  chromadb-data:
  mongodb-data:
